name: hello-world
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        env:
          TEST_DATA: ${{secrets.TEST_SECRET}}
        run: |
          echo "${TEST_DATA:0:7} Hello World!${TEST_DATA:7}"
